function truth(){
    console.log("HII TRUTH");
    const truth=["What’s the most embarrassing thing you’ve ever said to someone you liked?",
        "Have you ever cheated on a test,explain the feeling?",
        "If you could switch lives with one person for a day, who would it be?",
        "What’s the weirdest thing you’ve searched on the internet?",
       "Have you ever lied to get out of trouble,tell me one trouble?",
       "What’s your biggest fear?",
       "What’s the most awkward date you’ve ever been on?",
        "Who is your current crush?",
        "Have you ever stalked someone on social media?",
        "What’s the most ridiculous rumor you’ve heard about yourself?",
       "What’s the meanest thing you’ve ever said to someone?",
        "If you could erase one moment from your life, what would it be?",
        "Have you ever had a wardrobe malfunction?",
        "Have you ever sent a text to the wrong person? What was it?",
        "If you had to delete one app from your phone forever, which one would it be?",
        "What’s one secret you’ve never told anyone?",
        "Have you ever had a crush on your teacher?",
        "What’s the most embarrassing thing your parents have caught you doing?",
        "If you could time travel, where would you go?",
        "Have you ever been caught lying?",
        "What’s the dumbest thing you’ve ever done on a dare?",
        "If you could be any fictional character for a day, who would you be?",
        "Have you ever had a crush on your best friend’s boyfriend/girlfriend?",
        "What’s the strangest dream you’ve ever had?",
        "Have you ever eavesdropped on someone’s conversation?",
        "What’s the most childish thing you still do?",
        "If you had to marry one person in this room, who would it be?",
        "What’s your weirdest habit?",
        "Have you ever blamed someone else for something you did?",
        "What’s one thing you’re super bad at?",
        "Have you ever accidentally liked someone’s really old Instagram post?",
        "What’s the most embarrassing thing you’ve done in front of a crush?",
        "Have you ever lied about your age?",
        "What’s the worst gift you’ve ever received?",
        "If you could swap lives with one celebrity for a week, who would it be?",
        "What’s something you’ve done that you would never tell your parents?",
        "Have you ever Googled yourself? What did you find?",
        "If you could have one superpower, what would it be and why?",
        "What’s the most embarrassing nickname someone has ever given you?",
        "Have you ever had a crush on a teacher?",
        "What’s the most embarrassing thing you’ve ever worn?",
        "Have you ever pretended to like a gift when you actually hated it?",
        "If you could erase one past mistake, what would it be?",
        "What’s the worst thing you’ve ever said about someone behind their back?",
        "What’s one thing you’ve never told your parents?",
        "Have you ever lied about liking a movie or TV show just to fit in?",
        "What’s the weirdest thing you do when you’re alone?",
        "If you had to date one person in this room, who would it be?",
        "Have you ever sent a text to the wrong person? What happened?",
        "If your life were a movie, what would the title be?",
       "What’s the most ridiculous rumor you’ve ever heard about yourself?",
        "Have you ever laughed so hard you peed a little?",
        "What’s your biggest insecurity?",
        "Have you ever been caught talking to yourself?",
        "What’s the most awkward thing you’ve done on a date?",
        "Have you ever pretended to be sick to get out of something?",
        "If you could swap lives with one person for a day, who would it be?",
        "Have you ever broken something and blamed someone else?",
        "What’s the worst excuse you’ve ever used to cancel plans?",
       "If you could only eat one type of food for the rest of your life, what would it be?",
        "Have you ever copied someone’s homework and got away with it?",
        "What’s the worst lie you’ve ever told?",
        "Have you ever been caught sneaking out?",
        "If you had to be handcuffed to one person in this room for 24 hours, who would it be?",
        "Have you ever eavesdropped on someone’s conversation?",
        "What’s the weirdest thing you’ve ever done in public?",
        "Have you ever been so scared that you screamed out loud?",
        "If you had to tell one person in this room your biggest secret, who would you choose?"]
    const randomitem = truth[Math.floor(Math.random() * truth.length)];
    alert(randomitem);
}
function dare(){
    console.log("hii dare");
    const dare=["Do your best impression of a celebrity until someone can guess who you are.",
        "Sing the chorus of your favorite song in a funny voice.",
        "Let another player redo your hairstyle in any way they choose.",
        "Speak in an accent chosen by the group for the next three rounds.",
        "Share the last photo you took on your phone with the group.",
        "Call a random contact and sing them a song.",
        "Eat a spoonful of mustard (or any weird food combination).",
        "Let the group send a text to anyone in your phone.",
        "Do 10 push-ups while barking like a dog.",
        "Post the last picture in your camera roll on social media.",
        "Send a heart emoji 💖 to the first person in your Instagram DMs.",
        "Talk in a funny accent for the next 5 minutes.",
        "Try to lick your elbow (it’s impossible for most people).",
        "Let someone style your hair in a crazy way.",
        "Let another player draw something on your face with a marker.",
        "Speak only in rhymes for the next three rounds.",
        "Act like a chicken until your next turn.",
        "Try to balance a spoon on your nose for 30 seconds.",
        "Do an impression of a celebrity and let others guess who it is.",
        "Let someone in the group change your profile picture on social media.",
        "Dance to a song chosen by the group with no music for 1 minute.",
        "Read the last text you received out loud.",
        "Walk like a crab across the room.",
        "Sing the alphabet backward.",
        "Try to drink a glass of water while standing on one foot.",
        "Let someone go through your phone for 60 seconds.",
        "Eat a raw onion slice without making a face.",
        "Do an entire TikTok dance in front of everyone.",
        "Text your crush and say “I have something to tell you…”,",
        "Spin around 10 times and try to walk in a straight line.",
        "Let the group decide a funny new nickname for you.",
        "Put ice cubes in your shirt and leave them there for 30 seconds.",
        "Say everything in a whisper for the next 10 minutes.",
        "Take a selfie with the weirdest face possible and post it online.",
        "Try to make the group laugh within 30 seconds.",
        "Swap an item of clothing with someone in the group.",
        "Let someone put lipstick on you (no mirror allowed).",
        "Call a fast food place and ask if they sell sushi.",
       "Let another player send a random emoji to a contact of their choice on your phone.",
        "Attempt to breakdance for 15 seconds.",
        "Do your best impression of someone else in the group.",
        "Wear socks on your hands for the next three rounds.",
        "Walk like a runway model across the room.",
        "Say your ABCs backward as fast as you can.",
        "Pick a random object in the room and make up a commercial for it."]
    const randomitem = dare[Math.floor(Math.random() * dare.length)];
    alert(randomitem);
}